port: 7780

title: 潴頭在綫
description:
domain: kfitfk.github.io
url: https://kfitfk.github.io
author:
  name: Hao Ye
  uri: https://kfitfk.github.io

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag